name: Bug Report
description: File a bug report
title: "[REQ]: "
labels: ["Website request"]
assignees:
  - OhMyGuus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: Website URL
      description: The website u want to report
      placeholder: ex. google.com
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are u using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
        - Other

  - type: textarea
    id: notes
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true

