name: Bug Report
description: File a bug report
title: "[REQ]: "
labels: ["Website request"]
assignees:
  - OhMyGuus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: Website URL
      description: The website u want to report
      placeholder: ex. google.com
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browser are u using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.3
        - 1.0.4
        - 1.0.5
        - Latest
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Are things like videoplayback not working etc.
      placeholder:
    validations:
      required: false


